projetosite/fotos/urls.py
from django.urls import path
from . import views

app_name = 'fotos'
urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('index/', views.index, name='index'),
    path('galeria/', views.galeria, name='galeria'),
    path('galeria/foto/<str:pk>', views.verFoto, name='foto'),
    path('galeria/foto/<str:pk>/delete', views.removerFoto, name='eliminarFoto'),
    path('galeria/comunidade', views.comunidade, name='comunidade'),
    path('criar', views.criarFoto, name='criar'),
    path('registar', views.registar, name='registar'),
    path('login', views.user_login, name='login'),
    path('logout', views.process_logout, name='processlogout'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('profile/<str:pk>/edit', views.profile_edit, name='profile_edit'),
    path('galeria/foto/<str:pk>/comentario/', views.process_comentario, name='process_comentario'),
    path('403', views.no_perms_page, name='no_perms_page'),

]

projetosite/projetosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fotos.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projetosite/fotos/models.py
from django.contrib.auth import get_user_model
from django.utils.timezone import now
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Categoria(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.nome


class Foto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)
    imagem = models.ImageField(null=False, blank=False)
    titulo = models.CharField(max_length=250, null=False, blank=False)
    descricao = models.TextField()
    created_date = models.DateTimeField(default=now)
    likes = models.ManyToManyField(User, related_name='fotos_like')
    autor = models.ForeignKey(User, on_delete=models.CASCADE, default="")

    def number_of_likes(self):
        return self.likes.count()

    class Meta:
        ordering = ('created_date',)


class Rating(models.Model):
    foto = models.ForeignKey(Foto, on_delete=models.CASCADE)
    rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    user_rater = models.ForeignKey(User, on_delete=models.CASCADE)




class Comentario(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE, default="")
    texto = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    foto = models.ForeignKey(Foto, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='comentarios_like')

    def number_of_likes(self):
        return self.likes.count()


class Utilizador(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_img = models.ImageField(upload_to='profile/', blank=True)
    about = models.CharField(max_length=250, null=True, blank=True)
    followers = models.ManyToManyField(User, related_name='utilizador_followers')
    following = models.ManyToManyField(User, related_name='utilizador_following')

    def image_url(self):
        if self.profile_img and hasattr(self.profile_img, 'url'):
            return self.profile_img.url
        else:
            return '/static/images/profile/default.jpg'

    def number_of_followers(self):
        return self.followers.count()

    def number_of_following(self):
        return self.following.count()

    class Meta:
        permissions = [
            ("criar_post", "Pode criar posts"),
            ("criar_like_dislike", "Pode dar likes ou dislikes"),
            ("criar_comentario", "Pode criar comentários"),
            ("dar_follow", "Pode dar follow a outro utilizador")
        ]

projetosite/fotos/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    primeiro_nome = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    ultimo_nome = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

projetosite/fotos/views.py
import os
from django.db.models import Q
import django.urls
from django.views import View
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Categoria, Foto, Utilizador, Comentario, Rating
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect, Http404
from .forms import RegisterForm
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import user_passes_test


DEFAULT_PROFILE_URL = '/static/images/profile/default.jpg'


##################         FUNCOES        ##############################

# View 403
def no_perms_page(request):
    return render(request, 'fotos/no_perms.html')


# Ver se tem permissões!
def is_member(user):
    return user.groups.filter(name='utilizadores').exists()


# Função para remover a foto de perfil anterior, não remove a default
def delete_profile_img(utilizador):
    if utilizador.image_url != DEFAULT_PROFILE_URL:
        utilizador.profile_img.delete()


def is_staff(user):
    return user.groups.filter(name='utilizadores_staff').exists()



########################################################################

def inicio(request):
    return render(request, 'fotos/inicio.html')


# Frontpage
def index(request):
    categoria = request.GET.get('categoria')
    if categoria is None:
        fotos = Foto.objects.all()
    else:
        # Aplicar filtro
        fotos = Foto.objects.filter(categoria__nome__contains=categoria)

    categorias = Categoria.objects.all()
    context = {
        'categorias': categorias,
        'fotos': fotos
    }

    return render(request, 'fotos/index.html', context)


# Galeria
def galeria(request):
    # Filtro de categoria
    categoria = request.GET.get('categoria')
    # Filtro de sort
    sort = request.GET.get('sort')
    # Filtro de pesquisa
    pesquisa = request.GET.get('q')

    # Todas as categorias
    categorias = Categoria.objects.all()

    # Se não for dado filtro de categoria
    if categoria is None:
        fotos = Foto.objects.all()
    # Aplicar filtro de categoria
    else:
        fotos = Foto.objects.filter(categoria__nome__contains=categoria)
    # Aplicar filtro de sort
    if sort is not None:

        # Sort ascendente por data
        if sort == 'dataAscendente':
            fotos = Foto.objects.order_by('created_date')

        # Sort decrescente por data
        elif sort == 'dataDecrescente':
            fotos = Foto.objects.order_by('-created_date')

        # Sort por likes decrescente
        else:
            unsorted_fotos = fotos.all()
            fotos = sorted(unsorted_fotos, key=lambda t: t.number_of_likes(), reverse=True)

    # Filtro por pesquisa
    if pesquisa is not None:
        fotos = Foto.objects.filter(Q(titulo__icontains=pesquisa) | Q(autor__username__icontains=pesquisa))

    context = {
        'categorias': categorias,
        'fotos': fotos
    }

    return render(request, 'fotos/galeria.html', context)


# Lista de utilizadores
def comunidade(request):
    # Filtro de pesquisa
    pesquisa = request.GET.get('q')

    if pesquisa is None:
        utilizadores = Utilizador.objects.all()
    # Filtro por pesquisa
    else:
        utilizadores = Utilizador.objects.filter(user__username__icontains=pesquisa)

    context = {
        'utilizadores': utilizadores,
    }

    return render(request, 'fotos/comunidade.html', context)


# View que elimina comentário
@login_required(login_url=reverse_lazy('fotos:login'))
@user_passes_test(is_member, login_url=reverse_lazy('fotos:no_perms_page'))
def process_comentario(request, pk):
    comentario = get_object_or_404(Comentario, pk=pk)
    foto_id = comentario.foto.id
    liked = False
    # Dar like ou dislike
    if request.method == 'POST':
        # Se o user já deu like
        if comentario.likes.filter(id=request.user.id).exists():
            liked = True
        if liked is False:
            comentario.likes.add(request.user.id)
        else:
            comentario.likes.remove(request.user.id)

        return redirect('fotos:foto', foto_id)
    # Caso não seja para dar like ou dislike, é para remover
    if comentario.autor == request.user or request.user.is_superuser\
            or is_staff(request.user):
        comentario.delete()

    return redirect('fotos:foto', foto_id)


# View que elimina a foto
@login_required(login_url=reverse_lazy('fotos:login'))
@user_passes_test(is_member, login_url=reverse_lazy('fotos:no_perms_page'))
def removerFoto(request, pk):
    foto = get_object_or_404(Foto, pk=pk)
    if foto.autor == request.user or request.user.is_superuser or is_staff(request.user):
        foto.imagem.delete()
        foto.delete()
        return redirect('fotos:galeria')
    # Fazer 'refresh' para a página anterior
    return redirect(request.META['HTTP_REFERER'])


# Detalhe da foto
def verFoto(request, pk):
    foto = get_object_or_404(Foto, pk=pk)
    comentarios = Comentario.objects.filter(foto_id=pk).order_by('-created_date')
    likes = foto.number_of_likes()
    is_autor = False
    liked = False

    # Verifica se o user é o autor da foto
    if foto.autor == request.user:
        is_autor = True

    # Se o user já deu like
    if foto.likes.filter(id=request.user.id).exists():
        liked = True

    # Se houver um like ou dislike
    if request.method == 'POST':

        # Moderador faz rating da foto, criar ou alterar
        if request.POST.get('rating') is not None and is_staff(request.user):
            if Rating.objects.filter(foto_id=pk).exists():
                rating = Rating.objects.get(foto_id=pk)
                rating.rating = request.POST.get('rating')
                rating.user_rater_id = request.user.id
            else:
                rating, created = Rating.objects.get_or_create(
                    rating=request.POST.get('rating'),
                    user_rater_id=request.user.id,
                    foto_id=pk
                )
            rating.save()

        # Dar like só se ainda não deu like
        if request.POST.get('like') is not None and liked is False:
            foto.likes.add(request.user)

        # Dar Dislike se já deu like
        if request.POST.get('dislike') is not None and liked is True:
            foto.likes.remove(request.user)

        # Submit de um comentário, este está protegido pois os
        # botões para submit não são mostrados para utilizadores sem permissão
        if request.POST.get('texto') is not None:
            texto = request.POST.get('texto')
            comentario = Comentario(
                autor=request.user,
                texto=texto,
                foto=foto
            )
            comentario.save()

        # Fazer 'refresh' para a página anterior que era esta
        return redirect(request.META['HTTP_REFERER'])


    context = {
        'foto': foto,
        'likes': likes,
        'foto_is_liked': liked,
        'comentarios': comentarios,
        'is_autor': is_autor,
    }

    return render(request, 'fotos/foto.html', context)


@login_required(login_url=reverse_lazy('fotos:login'))
@user_passes_test(is_member, login_url=reverse_lazy('fotos:no_perms_page'))
def criarFoto(request):
    categorias = Categoria.objects.all()

    if request.method == 'POST':
        data = request.POST
        imagem = request.FILES.get('imagem')
        titulo = data['titulo']
        descricao = data['descricao']
        # Se for selecionado uma categoria existente
        if data['categoria'] != "none":
            categoria = Categoria.objects.get(id=data['categoria'])
        # Se for criado uma nova categoria, é utilizada essa
        elif data['novaCategoria'] != '':
            # Cria uma categoria se já não existir.
            # Se já existir, faz um get e coloca na variavel categoria
            categoria, created = Categoria.objects.get_or_create(nome=data['novaCategoria'])
        else:
            categoria = None

        foto = Foto.objects.create(
            categoria=categoria,
            titulo=titulo,
            descricao=descricao,
            imagem=imagem,
            autor=request.user
        )

        return redirect('fotos:galeria')

    context = {
        'categorias': categorias,
    }
    return render(request, 'fotos/criar.html', context)


def registar(request):
    template = 'fotos/registar.html'

    # Se alguém se registar
    if request.method == 'POST':

        form = RegisterForm(request.POST)
        foto_perfil = request.FILES.get('foto_perfil')
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Username já existe.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Email já existe.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Passwords não coincidem.'
                })
            else:
                user = User.objects.create_user(
                    username=form.cleaned_data['username'],
                    email=form.cleaned_data['email'],
                    first_name=form.cleaned_data['primeiro_nome'],
                    last_name=form.cleaned_data['ultimo_nome'],
                    password=form.cleaned_data['password'],
                )
                utilizador = Utilizador(user=user, profile_img=foto_perfil)

projetosite/fotos/templates/fotos/comunidade.html
{% extends 'base.html' %}

{% block title %} Comunidade {% endblock %}
{% load custom_tags %}
{% block content %}
<div class="container">
    <div class="row bootstrap snippets bootdeys">
        <div class="col-md-0 col-sm-0">
            <h2>Comunidade</h2>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <form action="{% url 'fotos:comunidade' %}" method="get">
                        <div class="input-group">
                            <input name="q" type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </button>
                        </div>
                    </form>
                </li>
            </ul>
        </div>
        {% for utilizador in utilizadores %}
        <div class="member-entry">
            <a href="{% url 'fotos:profile' utilizador.user_id %}" class="member-img">
                <img src="{{ utilizador.image_url }}" class="img-rounded">
                <i class="fa fa-forward"></i>
            </a>
            {% is_staff utilizador.user as is_moderator %}
            <div class="member-details">
                <h4>
                    <a style="font-size: 28px" href="{% url 'fotos:profile' utilizador.user_id %}">
                        {{ utilizador.user.username }}
                    </a>
                    {% if is_moderator %}
                    <span class="btn btn-sm btn-success ms-2"><i class="fa fa-user-shield"></i> Moderator</span>
                    {% endif %}
                </h4>
                <div class="row info-list">
                    <div class="col-sm-4">
                        <i class="fa fa-user"></i>
                        <a style="font-size: 18px" itemref=" ">{{ utilizador.user.first_name }} {{ utilizador.user.last_name }}</a>
                    </div>
                    <div class="col-sm-4">
                    </div>
                    <div class="col-sm-4">
                        <i class="fa fa-envelope"></i>
                        <a style="font-size: 18px" href=" ">{{ utilizador.user.email }}</a>
                    </div>
                    <div class="clear">
                    </div>
                    <div class="col-sm-4">
                        <p class="text-muted fs-13px"><i class="fa fa-history"> {{utilizador.user.last_login}}</i></p>
                    </div>
                    <div class="col-sm-4">
                    </div>
                    <div class="col-sm-4">
                        {% if request.user.is_authenticated %}
                        {% is_member request.user as is_allowed %}
                        {% if request.user.id != utilizador.user.id and is_allowed %}
                        <form action="{% url 'fotos:profile' utilizador.user_id %}" method="POST">
                            {% csrf_token %}
                            {% is_following request.user.id utilizador.user_id as validation %}
                            {% if validation %}
                            <button type="submit" name="unfollow" class="btn btn-primary">
                                Unfollow
                            </button>
                            {% else %}
                            <button type="submit" name="follow" class="btn btn-primary">
                                Follow
                            </button>
                            {% endif %}

                        </form>
                        {% endif %}
                        {% endif %}
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

projetosite/fotos/templates/fotos/criar.html
{% extends 'base.html' %}

{% block title %}
Adicionar foto
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card">
                <h1 class="text-center m-3">Adicionar foto</h1>
                <form method="POST" action="{% url 'fotos:criar' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group m-3">
                        <label for="titulo">Título</label>
                        <textarea required class="form-control" placeholder="Título" id="titulo"
                                  name="titulo"></textarea>
                    </div>

                    <div class="form-group m-3">
                        <label for="descricao">Descrição</label>
                        <textarea required class="form-control" placeholder="Descrição" id="descricao"
                                  rows="6" name="descricao"></textarea>
                    </div>

                    <div class="form-group m-3">
                        <label for="selectCategoria">Selecione uma categoria</label>
                        <select class="form-select form-select-sm "
                                aria-label=".form-select-sm"
                                name="categoria" id="selectCategoria">
                            <option selected value="none">Selecione uma categoria...</option>
                            {% for categoria in categorias %}
                            <option value="{{categoria.id}}">{{categoria.nome}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group m-3">
                        <label for="novaCategoria">Nova categoria</label>
                        <input name="novaCategoria" id="novaCategoria"
                               type="text" placeholder="Nova categoria"
                               class="form-control">
                    </div>

                    <div class="form-group m-3">
                        <div class="input-group input-group-sm mb-3">
                            <input required type="file" class="form-control" id="imagem" name="imagem">
                            <label class="input-group-text" for="imagem">Upload</label>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary m-3">Submeter</button>

                </form>
                <a href="{% url 'fotos:galeria' %}" class="btn btn-dark m-5">Voltar</a>
            </div>
        </div>
    </div>


</div>
{% endblock %}

projetosite/fotos/templates/fotos/galeria.html
{% extends 'base.html' %}

{% block title %}
Galeria
{% endblock %}
{% load custom_tags %}
{% block content %}
<div class="container">

    <div class="row">
        <!--sidebar com filtros-->
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    Procura por título
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <form action="{% url 'fotos:galeria' %}" method="get">
                            <div class="input-group">
                                <input name="q" type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            </div>
                        </form>
                    </li>
                    <div class="card-header">
                        Categorias
                    </div>
                    <li class="list-group-item">
                        <a href="{% url 'fotos:galeria' %}" class="hover_link">Todas</a>
                    </li>
                    {% for categoria in categorias %}
                    <li class="list-group-item">
                        <!--Mandar um GET-->
                        <a href="{% url 'fotos:galeria' %}?categoria={{categoria.nome}}" class="hover_link">
                            {{categoria.nome}}
                        </a>
                    </li>
                    {% endfor %}
                    <div class="card-header">
                        Sort
                    </div>
                    <li class="list-group-item">
                        <form action="{% url 'fotos:galeria' %}" method="get">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="sort" id="likes"
                                       value="likes">
                                <label class="form-check-label" for="likes">
                                    Mais relevantes
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="sort" id="dataAscendente"
                                       value="dataAscendente">
                                <label class="form-check-label" for="dataAscendente">
                                    Data ascendente
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="sort" id="dataDecrescente"
                                       value="dataDecrescente">
                                <label class="form-check-label" for="dataDecrescente">
                                    Data descendente
                                </label>
                            </div>
                            <button type="submit" class="btn btn-sm btn-primary btn-block mt-2">
                                Filtrar
                            </button>
                        </form>
                    </li>
                    {% is_member request.user as is_allowed %}
                    {% if user.is_authenticated and is_allowed %}
                    <li class="list-group-item">
                        <a href="{% url 'fotos:criar' %}" class="btn btn-dark btn-sm m-1">
                            Adicionar foto</a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="list-group-item">
                        <a href="{% url 'fotos:profile' request.user.id %}" class="btn btn-dark btn-sm m-1">
                            Perfil</a>
                        <a href="{% url 'fotos:processlogout' %}" class="btn btn-outline-dark btn-sm m-1">
                            Logout</a>
                    </li>
                    {% else %}
                    <li class="list-group-item">
                        <a href="{% url 'fotos:login' %}" class="btn btn-outline-dark btn-sm m-1">
                            Login</a>
                    </li>
                    {% endif %}


                </ul>
            </div>
        </div>

        <!--Galeria de fotos-->
        <div class="col-md-9">
            <div class="row">

                {% for foto in fotos %}
                <div class="col-md-4">
                    <div class="card my-2">
                        <img class="image-thumbnail" src="{{foto.imagem.url}}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">
                                {{foto.titulo}}<span class="badge rounded-pill bg-dark mx-2">{{foto.categoria.nome}}</span>
                            </h5>
                            <p><strong>Autor:</strong>
                                <span class="badge rounded-pill bg-primary mx-1">
                                    <a style="text-decoration: none; color: white"
                                       href="{% url 'fotos:profile' foto.autor.id %}">{{ foto.autor.username }}</a>
                                </span>
                            </p>
                            <p><strong>Data de upload:</strong> {{foto.created_date}}</p>
                            <p><strong>Likes:</strong> {{foto.number_of_likes}}</p>
                            <!--ELIMINAR FOTO-->
                            {% is_staff request.user as is_moderator %}
                            {% if user.is_authenticated and user.is_superuser or is_moderator %}
                            <a href="{% url 'fotos:eliminarFoto' foto.id %}" class="btn btn-danger"
                               onclick="return confirm('Tem a certeza que quer eliminar?')">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </a>
                            {% endif %}
                        </div>

                        <a href="{% url 'fotos:foto' foto.id %}" class="btn btn-outline-dark btn-sm m-1">Ver foto</a>
                    </div>
                </div>
                {% empty %}
                <h3>Não há fotos :/ ...</h3>
                {% endfor %}

            </div>


        </div>


    </div>
</div>
{% endblock %}

projetosite/fotos/templates/fotos/inicio.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Inicio</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/inicio.css' %}">
</head>
<body>
<div class="bg">
    <div class="link-container">
        <a class="link-one" href="{% url 'fotos:index' %}"><div class="bg-text">FStoppers</div></a>
    </div>
</div>
</body>
</html>

projetosite/fotos/templates/fotos/login.html
{% extends "base.html" %}
{% block title %}
Login
{% endblock %}
{% block nav %}
{% endblock %}
{% block body %}
<body>
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 col-md-7 intro-section">
            <div class="brand-wrapper">
                <a href="{% url 'fotos:inicio' %}" style="text-decoration: none; color: white">
                    <h1>FStoppers</h1>
                </a>

            </div>
            <div class="intro-content-wrapper">
                <h1 class="intro-title">Bem vindo ao <strong style="color: #14C8CE;">FStoppers</strong>!</h1>
                <p class="intro-text">Área dos fotógrafos para partilharem as suas melhores fotos.</p>
                <a href="{% url 'fotos:galeria' %}" class="btn btn-read-more">Saber mais</a>
            </div>
            <div class="intro-section-footer">
                <na class="footer-nav">
                    <a href="https://www.facebook.com/ISCTEIUL/" target="_blank" >Facebook</a>
                    <a href="https://twitter.com/ISCTEIUL" target="_blank" >Twitter</a>
                    <a href="mailto: geral@iscte.pt.com" target="_blank" >Gmail</a>
                </na>
            </div>
        </div>
        <div class="col-sm-6 col-md-5 form-section">
            <div class="login-wrapper">
                <h2 class="login-title">Login</h2>
                <form action="{% url 'fotos:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username" class="sr-only">Username</label>
                        <input id="username" name="username" value="" type="text" class="form-control" placeholder="Username"/>
                    </div>
                    <div class="form-group mb-3">
                        <label for="password" class="sr-only">Password</label>
                        <input type="password" name="password" id="password" class="form-control" placeholder="Password">
                    </div>
                    <div class="d-flex justify-content-between align-items-center mb-5">
                        <input name="login" id="login" class="btn login-btn" type="submit" value="Login">
                    </div>
                </form>

                {% if error_message %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Holy guacamole!</strong> Algo não funciona...<br>
                    <u>{{ error_message }}</u>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}

                <p class="login-wrapper-footer-text">Não tem conta?
                    <a href="{% url 'fotos:registar' %}" class="text-reset">Registe aqui</a>
                </p>

            </div>
        </div>
    </div>
</div>
{% endblock %}
</body>
{% endblock %}